#!/bin/bash

# Load the GitHub token from a file
TOKEN_FILE="/root/token/token_file.txt"
GITHUB_TOKEN=$(cat "$TOKEN_FILE")

# Set the repository path
REPO_PATH=$(git rev-parse --show-toplevel)

# Extract the repository name from the path
REPO_NAME=$(basename "$REPO_PATH")

# Set the commit message and branch
read -p "Enter the commit message: " COMMIT_MESSAGE
BRANCH="master"

# Add and commit changes
git -C "$REPO_PATH" add .
git -C "$REPO_PATH" commit -m "$COMMIT_MESSAGE"

# Push to GitHub using the token
GIT_URL="https://$GITHUB_TOKEN:x-oauth-basic@github.com/globalsmile/$REPO_NAME.git"
git -C "$REPO_PATH" push "$GIT_URL" "$BRANCH"

