#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello World!.
#

sudo apt-get -y update
sudo apt-get -y install nginx
file1=/usr/share/nginx/html/index.html
sudo bash -c "echo 'Hello World!' > $file1"
service nginx start
