#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello World!.
#

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start
echo "Hello World!" > /var/www/html/index.html
sed -i 's/80/80/g' /etc/nginx/sites-enabled/default
service nginx reload

